version: "3.8"
services:
  postgres:
    container_name: pg
    image: postgres:14.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_db
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - ./data-postgres:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - oidc-network
  provider:
    image: provider
    container_name: oidc-provider
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run build:local-server
    environment:
      NODE_ENV: dev
      DATABASE_URL: postgresql://postgres:postgres@pg:5432/postgres_db?schema=prod
      PORT: 8080
      PUBLIC_KEY: '{
                    "crv": "P-256",
                    "ext": true,
                    "key_ops": [
                        "verify"
                    ],
                    "kid": "fugRbj0jKFx-rN7BBKej35c_nzI6sHBievLH7GfOTbs",
                    "kty": "EC",
                    "x": "nMz83GVY8DJUntJLc2eAH4Z6AnidIxu9HHo9-uaaWnU",
                    "y": "JolU0OhmmEhBd4Pj5OCEYcF12aiAoLp6b1BqCFZh9Yk"
                  }'
      PRIVATE_KEY: '{
                    "crv": "P-256",
                    "d": "co1-IO5jWYCSqT34Q02rjvBdgaiu2GXdzcHmLfn6_OM",
                    "ext": true,
                    "key_ops": [
                        "sign"
                    ],
                    "kid": "fugRbj0jKFx-rN7BBKej35c_nzI6sHBievLH7GfOTbs",
                    "kty": "EC",
                    "x": "nMz83GVY8DJUntJLc2eAH4Z6AnidIxu9HHo9-uaaWnU",
                    "y": "JolU0OhmmEhBd4Pj5OCEYcF12aiAoLp6b1BqCFZh9Yk"
                    }'
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - oidc-network
networks:
  oidc-network:
volumes:
  db:
